// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             v4.24.4
// source: assistant.proto

package assistant

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// AssistantClient is the client API for Assistant service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AssistantClient interface {
	Handle(ctx context.Context, in *AssistantRequest, opts ...grpc.CallOption) (*AssistantResponse, error)
}

type assistantClient struct {
	cc grpc.ClientConnInterface
}

func NewAssistantClient(cc grpc.ClientConnInterface) AssistantClient {
	return &assistantClient{cc}
}

func (c *assistantClient) Handle(ctx context.Context, in *AssistantRequest, opts ...grpc.CallOption) (*AssistantResponse, error) {
	out := new(AssistantResponse)
	err := c.cc.Invoke(ctx, "/Assistant/Handle", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AssistantServer is the server API for Assistant service.
// All implementations must embed UnimplementedAssistantServer
// for forward compatibility
type AssistantServer interface {
	Handle(context.Context, *AssistantRequest) (*AssistantResponse, error)
	mustEmbedUnimplementedAssistantServer()
}

// UnimplementedAssistantServer must be embedded to have forward compatible implementations.
type UnimplementedAssistantServer struct {
}

func (UnimplementedAssistantServer) Handle(context.Context, *AssistantRequest) (*AssistantResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Handle not implemented")
}
func (UnimplementedAssistantServer) mustEmbedUnimplementedAssistantServer() {}

// UnsafeAssistantServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AssistantServer will
// result in compilation errors.
type UnsafeAssistantServer interface {
	mustEmbedUnimplementedAssistantServer()
}

func RegisterAssistantServer(s grpc.ServiceRegistrar, srv AssistantServer) {
	s.RegisterService(&Assistant_ServiceDesc, srv)
}

func _Assistant_Handle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AssistantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AssistantServer).Handle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/Assistant/Handle",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AssistantServer).Handle(ctx, req.(*AssistantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Assistant_ServiceDesc is the grpc.ServiceDesc for Assistant service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Assistant_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "Assistant",
	HandlerType: (*AssistantServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Handle",
			Handler:    _Assistant_Handle_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "assistant.proto",
}
